<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('actions')->delete();

        \DB::table('actions')->insert([
            0 => [
                'id' => 1,
                'name' => 'Create',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'Update',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'Delete',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'Login',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'Logout',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'Follow',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'name' => 'Unfollow',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'name' => 'Attending',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'name' => 'Unattending',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'name' => 'Activate',
                'object_table' => 'User',
                'child_object_table' => null,
                'description' => 'Activate user',
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'name' => 'Suspend',
                'object_table' => 'User',
                'child_object_table' => null,
                'description' => 'Suspend user',
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'name' => 'Reminder',
                'object_table' => 'User',
                'child_object_table' => null,
                'description' => 'Email reminder',
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'name' => 'Impersonate',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 14,
                'name' => 'Failed Login',
                'object_table' => null,
                'child_object_table' => null,
                'description' => null,
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 15,
                'name' => 'Notification',
                'object_table' => null,
                'child_object_table' => null,
                'description' => 'Email notification',
                'changes' => null,
                'order' => 0,
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
