<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert([
            0 => [
                'id' => 1,
                'name' => 'show_user',
                'label' => 'Show User',
                'description' => 'Show User',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            1 => [
                'id' => 2,
                'name' => 'edit_user',
                'label' => 'Edit User',
                'description' => 'Edit User',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            2 => [
                'id' => 3,
                'name' => 'show_event',
                'label' => 'Show Event',
                'description' => 'Show Event',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            3 => [
                'id' => 4,
                'name' => 'edit_event',
                'label' => 'Edit Event',
                'description' => 'Edit Event',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            4 => [
                'id' => 5,
                'name' => 'show_tag',
                'label' => 'Show Tag',
                'description' => 'Show Tag',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            5 => [
                'id' => 6,
                'name' => 'edit_tag',
                'label' => 'Edit Tag',
                'description' => 'Edit Tag',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            6 => [
                'id' => 7,
                'name' => 'show_series',
                'label' => 'Show Series',
                'description' => 'Show Series',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            7 => [
                'id' => 8,
                'name' => 'edit_series',
                'label' => 'Edit Series',
                'description' => 'Edit Series',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            8 => [
                'id' => 9,
                'name' => 'show_entity',
                'label' => 'Show Entity',
                'description' => 'Show Entity',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            9 => [
                'id' => 10,
                'name' => 'edit_entity',
                'label' => 'Edit Entity',
                'description' => 'Edit Entity',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            10 => [
                'id' => 11,
                'name' => 'show_forum',
                'label' => 'Show Forum',
                'description' => 'Show Forum',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            11 => [
                'id' => 12,
                'name' => 'edit_forum',
                'label' => 'Edit Forum',
                'description' => 'Edit Forum',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            12 => [
                'id' => 13,
                'name' => 'show_permission',
                'label' => 'Show Permission',
                'description' => 'Show Permission',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            13 => [
                'id' => 14,
                'name' => 'edit_permission',
                'label' => 'Edit Permission',
                'description' => 'Edit Permission',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            14 => [
                'id' => 15,
                'name' => 'show_group',
                'label' => 'Show Group',
                'description' => 'Show Group',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            15 => [
                'id' => 16,
                'name' => 'edit_group',
                'label' => 'Edit Group',
                'description' => 'Edit Group',
                'level' => 10,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            16 => [
                'id' => 17,
                'name' => 'show_activity',
                'label' => 'Show Activity',
                'description' => 'Show Activity',
                'level' => 1,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            17 => [
                'id' => 18,
                'name' => 'show_admin',
                'label' => 'Show Admin',
                'description' => 'Show Admin',
                'level' => 100,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            18 => [
                'id' => 19,
                'name' => 'trust_post',
                'label' => 'Trust Post',
                'description' => 'Trust Post',
                'level' => 90,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            19 => [
                'id' => 20,
                'name' => 'trust_thread',
                'label' => 'Trust Thread',
                'description' => 'Trust Thread',
                'level' => 90,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            20 => [
                'id' => 21,
                'name' => 'grant_access',
                'label' => 'Grant Access',
                'description' => 'Grant Access',
                'level' => 999,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            21 => [
                'id' => 22,
                'name' => 'grant_event_ownership',
                'label' => 'Grant Event Ownership',
                'description' => 'Grant Event Ownership',
                'level' => 100,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            22 => [
                'id' => 23,
                'name' => 'grant_entity_ownership',
                'label' => 'Grant Entity Ownership',
                'description' => 'Grant Entity Ownership',
                'level' => 100,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
            23 => [
                'id' => 24,
                'name' => 'grant_series_ownership',
                'label' => 'Grant Series Ownership',
                'description' => 'Grant Series Ownership',
                'level' => 100,
                'created_at' => '2017-06-04 23:47:11',
                'updated_at' => '2017-06-04 23:47:11',
            ],
        ]);
    }
}
