name: Build Prod
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Prod
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/events-tracker
            git checkout main
            git remote update
            git pull
            npm run prod
